[build]
  # 1) aplica migrações no Supabase
  # 2) roda o build do Next.js
  command = "npx prisma migrate deploy && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
